version: '3.7'

services:
  local-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  local-kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: local-zookeeper:2181
    depends_on:
      - local-zookeeper
    volumes:
      - kafkadata:/kafka